// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Eventer',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {

//   return (
//     <html lang="en">
//       <body suppressHydrationWarning={true} className={inter.className}>{children}</body>
//     </html>
//   )
// }


import * as React from 'react';
import ThemeRegistry from './components/ThemeRegistry/ThemeRegistry';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/header/header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Eventer',
  description: 'Next.js App Router + Material UI v5',
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <ThemeRegistry>
          <Header />
            {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
